### ISSUE TITLE
Missing docker images

### ISSUE THREAD

**Issue by datachi7d** [CreatorDev/DeviceServer#7]
I cannot find the dockerfiles to build flowops/dockerconsul and flowops/dockerfabio as I do not have access to the Hemel docker registry. Are these available?

**Comment by datachi7d** [comment]
@GonZo, @boyvinall, @cheekyhalf - any of you have these dockerfiles?

**Comment by GonZo** [comment]
Hi @datachi7d 
We are in the process of publishing them. I will ping you when they are published.

**Comment by datachi7d** [comment]
Thanks @GonZo. I have removed some of the other dependencies on the Hemel docker registry - should I open a pull request?

**Comment by GonZo** [comment]
@datachi7d yes  that would be great

**Comment by boyvinall** [comment]
Fixed by #11
